spring:
  # 选择加载不同环境的配置文件
  profiles:
    active: dev

  # MVC相关配置
  mvc:
    # 配置ICO
    favicon:
      enabled: false
  http:
    # 配置上传文件限制大小
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 配置热部署
  devtools:
    restart:
      # 如果改为true则当修改java目录下的文件时会自动进行重启
      enabled: false
      additional-paths: src/main/java

  # 数据方面的配置
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池的配置信息
    maxActive: 20
    initialSize: 5
    minIdle: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.linkinstars.springBootTemplate.bean

pagehelper:
    helperDialect: mysql