# 开发环境配置
server:
  port: 8088
spring:
#userSSL=true 需要进行安全性配置
  datasource:
        url: jdbc:mysql://127.0.0.1:3306/advert_chain?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password:
  #redis相关配置
  redis:
    host: localhost
    port: 6379
    pool:
      # 最大连接数（负值表示没有限制）
      max-active: 8
      # 最大阻塞等待时间（负值表示没有限制）
      max-wait: 1
      # 最大空闲链接
      max-idle: 8
      # 最小空闲链接
      min-idle: 0
    # 链接超时时间（毫秒）
    timeout: 0